### ISSUE TITLE
一个单词拼写错误：CATEGORY = "Promat-translate"

### ISSUE THREAD

**Issue by amimi818** [pengchengmi/ComfyUI_Prompt_Translate_to_English#1]
简单实用的一个节点扩展，超好用！

**Comment by pengchengmi** [comment]
> 

谢谢，过两天有空整理一个不需要 api的版本。

**Comment by pengchengmi** [comment]
我改一下

**Comment by pengchengmi** [comment]
已修改，谢谢提醒！

**Comment by amimi818** [comment]
> > 
> 
> 谢谢，过两天有空整理一个不需要 api的版本。

那将更好了。

另外，我对comfyui的自定义节点编写不熟，不知道能不能在同一个节点上，把翻译结果显示出来（无需再外连show text节点了）。我尝试了一下没有搞定，好像得编写JS。

**Comment by pengchengmi** [comment]
> 
我找个时间研究一下，最好是能直接在里面编辑的，若编辑权重就有些麻烦了
