### ISSUE TITLE
PreviewText screen freezes

### ISSUE THREAD

**Issue by hben35096** [pengchengmi/ComfyUI_Prompt_Translate_to_English#2]
情况和下面这个插件出现的问题一样，就是运行后，会出现UI界面卡住
https://github.com/AlekPet/ComfyUI_Custom_Nodes_AlekPet/issues/5
![image](https://github.com/pengchengmi/ComfyUI_Prompt_Translate_to_English/assets/139383150/cff53abb-51f1-4015-93e2-6ef821959102)
而能够正常使用的只有Custom-Scripts的文本显示节点。

**Comment by pengchengmi** [comment]
我试一下，那个作者解决了这个问题吗

**Comment by hben35096** [comment]
> 我试一下，那个作者解决了这个问题吗
刚安装试了一下，那个插件现在不会冻结，但完全失效了

**Comment by pengchengmi** [comment]
> > 我试一下，那个作者解决了这个问题吗
> > 刚安装试了一下，AlekPet那个插件的显示文件节点现在不会冻结，但如果在阿里云服务器不使用内网穿透之类的打开ComfyUI界面，这个节点就无法显示。
> > 而Custom-Scripts的文本显示，在任何模式下都经得住考验。

这是什么神奇问题，节点里不存在联网的操作阿😢😢😢

**Comment by pengchengmi** [comment]
> 情况和下面这个插件出现的问题一样，就是运行后，会出现UI界面卡住 [AlekPet/ComfyUI_Custom_Nodes_AlekPet#5](https://github.com/AlekPet/ComfyUI_Custom_Nodes_AlekPet/issues/5) ![image](https://user-images.githubusercontent.com/139383150/269701208-cff53abb-51f1-4015-93e2-6ef821959102.png) 而能够正常使用的只有Custom-Scripts的文本显示节点。

----
我换了一个 文本预览节点的实现方式，可以更新一下看看还会不会冻结😊😊😊

**Comment by hben35096** [comment]
> > 情况和下面这个插件出现的问题一样，就是运行后，会出现UI界面卡住 [AlekPet/ComfyUI_Custom_Nodes_AlekPet#5](https://github.com/AlekPet/ComfyUI_Custom_Nodes_AlekPet/issues/5) ![image](https://user-images.githubusercontent.com/139383150/269701208-cff53abb-51f1-4015-93e2-6ef821959102.png) 而能够正常使用的只有Custom-Scripts的文本显示节点。
> 
> 我换了一个 文本预览节点的实现方式，可以更新一下看看还会不会冻结😊😊😊
问题完美解决了，现在效果非常棒，谢谢~
![image](https://github.com/pengchengmi/ComfyUI_Prompt_Translate_to_English/assets/139383150/e0059a9b-505c-4473-ae0a-bf5bd01d691a)

**Comment by hben35096** [comment]
> > > 我试一下，那个作者解决了这个问题吗
> > > 刚安装试了一下，AlekPet那个插件的显示文件节点现在不会冻结，但如果在阿里云服务器不使用内网穿透之类的打开ComfyUI界面，这个节点就无法显示。
> > > 而Custom-Scripts的文本显示，在任何模式下都经得住考验。
> 
> 这是什么神奇问题，节点里不存在联网的操作阿😢😢😢
阿里云实例给出的网页链接，确实经常会有各种显示问题，比如webui里的infinite-image-browsing和ControlNet里的openpose编辑，都是无法显示的；而ComfyUI，载入图像节点的遮罩绘制窗口也是无法打开的，好像是和js什么的有关。现在你这个插件在任何模式下都运行得很好。
