### ISSUE TITLE
请问作者大大。这个可以使用阿里云翻译的api吗？

### ISSUE THREAD

**Issue by DTTZLS** [pengchengmi/ComfyUI_Prompt_Translate_to_English#3]
请问作者大大。这个可以使用阿里云翻译的api吗？还是说只能用百度云的？

**Comment by hben35096** [comment]
同问，可以使用腾讯API翻译吗？百度额度用完了...

**Comment by pengchengmi** [comment]
> 同问，可以使用腾讯API翻译吗？百度额度用完了...

可以是可以，有时间做一个，最近没时间，多催下我。

**Comment by pengchengmi** [comment]
有大佬写了这个功能，你们可以试下
